common:
  ssh_key: "../../../credentials/ssh_key.txt"
  ssh_key_pub: "../../../credentials/ssh_key.pub.txt"
gcp:
  terraform_bucket: "global-unique-key-opendax-terraform"
  credentials: "../../../credentials/gcp.json"
  project: "opendax"
  region: "asia-northeast1"
  zone: "asia-northeast1-a"
  image: "debian-cloud/debian-10"
hcloud:
  token: "../../../credentials/hcloud_token.txt"
  ssh_fingerprint: "../../../credentials/hcloud_ssh_fingerprint.txt"
  region: "fsn1"
  zone: "fsn1-dc1"
  image: "debian-10"
  network: "10.0.1.0/24"
cloudflare:
  token: "../../../credentials/cloudflare_token.txt"
